#!/usr/bin/env python3
import sys
import os
from pathlib import Path
# RPSE RENAME AND PAIR SUBTITLES AND EPISODES
# todo: adicionar suporte para arquivos zip
#       opção pra modificar o delay das legendas


def fetch_dir(input_file):
    target_first_file = Path(input_file)
    file_dir = Path(os.path.dirname(target_first_file))

    file_buffer = []

    for i in file_dir.iterdir():
        if(i.suffix == target_first_file.suffix):
            file_buffer.append(Path(i))

    file_buffer.sort()

    t_first_file_index = file_buffer.index(target_first_file)
    return file_buffer[t_first_file_index:]


def print_dir(target_file1):
    for i in target_file1:
        print(i)


if (len(sys.argv) < 3):
    exit(1)

# primeiro arquivo especificado
source_dir = []
# segundo arquivo especificado
dest_dir = []

dump = False

for i in sys.argv[1:]:
    if (i == "-p"):
        dump = True
    elif not source_dir:
        source_dir = fetch_dir(i)
    elif not dest_dir:
        dest_dir = fetch_dir(i)

if (dump):
    print_dir(source_dir)
    print_dir(dest_dir)
    print(len(source_dir))
    print(len(dest_dir))
    exit(0)

for i in range(min(len(source_dir), len(dest_dir))):
    # local do destino + nome da origem + extensao do destino
    dest_dir[i].rename(
            dest_dir[0].parent / Path(
                source_dir[i].name).with_suffix(
                dest_dir[0].suffix))
